apiVersion: v1
kind: Pod
metadata:
  name: xc16-mplabx-sonar-fmpp-python
spec:
  containers:
    - name: xc16-mplabx-sonar-fmpp-python
      image:  artifacts.microchip.com:7999/microchip/citd/bundles/xc16-mplabx-sonar-fmpp-python-yarn-node:latest
      imagePullPolicy: Always
      command: ['cat']
      tty: true
      resources:
        requests:
          cpu: 1
          memory: 1Gi
        limits:
          cpu: 2
          memory: 2Gi
