////////////////////////////////////////////////////////////////////////////////
// © 2019 Microchip Technology Inc. and its subsidiaries.
//
// MICROCHIP SOFTWARE NOTICE AND DISCLAIMER: Subject to your compliance with 
// these terms, you may use Microchip software and any derivatives exclusively 
// with Microchip products. It is your responsibility to comply with third party
// license terms applicable to your use of third party software (including open 
// source software) that may accompany Microchip software.
//
// THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS". NO WARRANTIES, WHETHER
// EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY
// IMPLIED WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS
// FOR A PARTICULAR PURPOSE.
//
// IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE,
// INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND
// WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP
// HAS BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE. TO
// THE FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL
// CLAIMS IN ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT
// OF FEES, IF ANY, THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS
// SOFTWARE.
////////////////////////////////////////////////////////////////////////////////

#define PWM_PIN_IO 0
#define PWM_PIN_PWM 1
#define MODE_PUSHPULL 2
#define DEADTIME_DISABLE 2
#define IUE_ENABLE 1
#define IUE_DISABLE 0
#define EIPU_ENABLE 1
#define EIPU_DISABLE 0
#define PRIMARY_TIMEBASE 0
#define SWAP_ENABLE 1
#define PWM_MODULE_ENABLE 1
#define PWM_MODULE_DISABLE 0
#define PWM_PIN_OVERDAT_LOW 0
#define PWM_PIN_OVERDAT_HIGH 1
#define PWM_FAULTMODE_LATCH 0
#define PWM_FAULTMODE_CYCLE 1
#define PWM_FAULTMODE_DISABLE 2
#define PWM_FAULTSOURCE_HIGH 0
#define PWM_FAULTSOURCE_LOW 1

#define PWM_FAULTSOURCE_ACMP1 0b01101

#define TRIGSTART_DELAY_1PWM 1
#define TRIGOUTPUT_EVENT_2 1

#define SEVT_EVERY_COMPARE_MATCH 0
#define SEVT_1SKIP_COMPARE_MATCH 1

#define INTERRUPT_ENABLE 1
#define INTERRUPT_DISABLE 0
#define INTERRUPT_PRIORITY_3 3
#define INTERRUPT_PRIORITY_4 4
#define INTERRUPT_PRIORITY_5 5
#define INTERRUPT_PRIORITY_6 6
#define INTERRUPT_PRIORITY_7 7
#define INTERRUPT_FLAG_CLEAR 0
#define INTERRUPT_FLAG_SET 1

#define TIMER_RESET 0
#define TIMER_IDLEMODE_DISABLE 0
#define TIMER_MODULE_ENABLE 1
#define TIMER_MODULE_DISABLE 0
#define TIMER_PRESCALER_1BY1 0
#define TIMER_PRESCALER_1BY8 1
#define TIMER_PRESCALER_1BY64 2
#define TIMER_PRESCALER_1BY256 3
#define TIMER_GATEDTIME_DISABLE 0
#define TIMER_GATEDTIME_ENABLE 1
#define TIMER_INTERNAL_CLOCK 0
#define TIMER_EXTERNAL_CLOCK 1

#define IO_PIN_OUTPUT 0
#define IO_PIN_INPUT 1


#define ADC_MODULE_ENABLE 1
#define ADC_MODULE_DISABLE 0
#define ADC_TRIGGERSOURCE_PWM1 5
#define ADC_TRIGGERSOURCE_PWM2 6
#define ADC_INTGER_FORM 0
#define ADC_12BIT_RESOLUTION 3
#define ADC_EARLYINT_ENABLE 1
#define ADC_EARLYINT_DISABLE 0
#define ADC_REFVOLT_AVDD 0
#define ADC_CORECLOCK_1BY2 0
#define ADC_CLOCKSOURCE_OSCILLATOR 1
#define ADC_CLOCKSOURCE_FRC 2
#define ADC_CLOCKDIV_1BY1 0
#define ADC_ALLCHANNEL_SINGLE_UNSIGNED 0x0000

#define ADC_CALI_WARMUP 11
#define ADC_CORE_POWER_ENABLE 1
#define ADC_CORE_POWER_DISABLE 0
#define ADC_CORE_ENABLE 1
#define ADC_CORE_DISABLE 0
#define ADC_CORE_CALI_ENABLE 1
#define ADC_CORE_CALI_DISABLE 0
#define ADC_CORE_CALI_SINGLEMODE 0
#define ADC_CORE_CALI_DIFFMODE 1
#define ADC_CORE_CALI_START 1

#define ACLOCK_ASRCSEL_PRIMARY 1
#define ACLOCK_FRCSEL_PRIMARY 0
#define ACLOCK_FRCSEL_FRC 1
#define ACLOCK_DIVSOURCE_APLL 1
#define ACLOCK_DIVSOURCE_FVCO 0
#define ACLOCK_DIVIDER_BY1 7
#define APLL_ENABLE 1
#define APLL_DISABLE 0
#define NEWOSC_PRIMARY_WITHPLL 0x03
#define CURRENTOSC_PRIMARY_WITHPLL 0b011
#define NEWOSC_PRIMARY_NOPLL 0x02
#define NEWOSC_FRC_WITHPLL 0x01
#define NEWOSC_FRC_NOPLL 0x00
#define NEWOSC_SWITCH_ENABLE 0x01

void InitCalibrateADC(void);
void InitAltRegContext1Setup(void);


